### ISSUE TITLE
No visible @interface for 'Branch' declares the selector 'enableLogging', 'addFacebookPartnerParameterWithName:value:', 'clearPartnerParameters'

### ISSUE THREAD

**Issue by csritter** [BranchMetrics/unity-branch-deep-linking-attribution#195]
Hi, I've updated with the last Branch version (0.6.7) and iOS build have a strange issue which doesn't found 3 interfaces methods.

<img width="500" alt="Screen Shot 2022-01-28 at 19 02 39" src="https://user-images.githubusercontent.com/73347739/151627844-e9e6dc28-5981-47e3-b3f4-ff04f4647101.png">

This issues its found in Unity 2020.3.26f1, Xcode 12.4/13.2.

Any ideas to solve this problem?

**Comment by echo-branch** [comment]
We did make a change to how we resolve our dependencies and it looks to me like you're still getting an old version of the underlying Branch iOS SDK. I didn't see that error when testing upgrade scenarios, but may have missed your setup. Which version were you upgrading from?

We now depend on Google's unity external dependency manager.
https://github.com/googlesamples/unity-jar-resolver

**Comment by csritter** [comment]
The version was 0.6.4.
So download the external dependecy manager from this repository?

**Comment by echo-branch** [comment]
That's usually not necessary since it should be included by the unitypackage. Check if you can find the menu for dependency resolution. Follow Google's documentation on updating the dependencies. 

Might need a docs update to make this process more clear.

![Screen Shot 2022-01-28 at 3 15 36 PM](https://user-images.githubusercontent.com/43450805/151634487-9f093fae-af2b-4152-80b7-c220cf17a363.png)

**Comment by csritter** [comment]
Thanks @echo-branch for the support.
I removed all the Branch folders, re-imported again and update google external dependency, and it looks like it's working now.
I believe it's an old file that was included with it.
Sorry for bother you.
